apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wise-panther-python 
  janus-idp.io/tekton: wise-panther-python
  backstage.io/kubernetes-id: wise-panther-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: wise-panther-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  