apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wise-panther-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wise-panther-python 
  name: wise-panther-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wise-panther-python 
